// <auto-generated />
namespace BabyInABag.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderquantity1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderquantity1));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131824286_orderquantity1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
